Feature: User Authentication Implementation
benzybert/tea-haven-frontend pull request #2
Opened 2024-12-24 08:46 UTC by benzybert

## Description
This PR implements user authentication functionality in the Tea Haven frontend application. The implementation includes user registration, login, and session management features to enhance security and user experience.

### Changes Made
- Added authentication-related components (Login, Register, ForgotPassword)
- Implemented JWT token handling and storage
- Added protected route components
- Integrated with backend authentication endpoints
- Added user context for global state management
- Implemented form validation and error handling

### Features
- User registration with email verification
- Secure login with JWT token authentication
- Password reset functionality
- Protected routes for authenticated users
- Persistent login state
- Form validation and error messaging

### Testing
- Unit tests for authentication components
- Integration tests for API endpoints
- Manual testing of authentication flow
- Cross-browser compatibility testing

### Security Considerations
- Implemented secure token storage
- Added CSRF protection
- Proper error handling
- Input validation and sanitization

### Dependencies
- Added required authentication-related packages
- Updated existing dependencies

### Documentation
- Updated README with authentication setup instructions
- Added JSDoc comments for new components
- Updated API documentation

## How to Test
1. Clone the branch
2. Run `npm install`
3. Start the development server
4. Test registration flow
5. Test login flow
6. Test protected routes
7. Test logout functionality

## Checklist
- [x] Code follows project style guidelines
- [x] Tests have been added and are passing
- [x] Documentation has been updated
- [x] Security best practices have been followed
- [x] Cross-browser testing completed
- [x] No console errors or warnings
- [x] Code review requested

## Related Issues
Closes #[issue_number] (Please link the related issue)

## Screenshots
(Please add relevant screenshots of the UI components)

2024-12-26 19:22 UTC, alesha712 commented
hi there

2024-12-26 19:24 UTC, alesha712 requested changes

2024-12-26 19:24 UTC, alesha712 commented on src/App.jsx
- Move the routing logic to `Router.jsx`.
- Create a `Layout` component for the `Header` and the `Footer`.
- `Header` and `Footer` are shared components that will probably be applied in multiple pages.

### `Layout.jsx` example:
```jsx
import React from 'react';
import Header from './Header';
import Footer from './Footer';

const Layout = ({ children }) => {
  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      <main className="flex-grow">{children}</main>
      <Footer />
    </div>
  );
};

export default Layout;
```

And use it in the Router.jsx like:
```jsx
function Router() {
  return (
    <BrowserRouter>
      <Layout>
        <Routes>
          {/* All routes here */}
          <Route path="*" element={<NotFound />} />
        </Routes>
      </Layout>
    </BrowserRouter>
  );
}
```

2024-12-26 19:24 UTC, alesha712 commented on src/App.jsx
> +import LoginForm from './components/presentational/auth/LoginForm';  // Fix path
DId you forget to fix the path? or are you planing to do it later?
(its better to not include these kind of comment as its confusing for the co-workers)

2024-12-26 19:24 UTC, alesha712 commented on src/components/container/features/tea/TeaList.jsx
> +        const response = await axios.get('http://localhost:5001/api/teas/search', {
You don't use the hook created. 
Make sure to follow the separtion of concern principle and the single responsability protocol.

2024-12-26 19:24 UTC, alesha712 commented on src/components/container/features/tea/TeaList.jsx
> +    : teas.filter(tea => tea.category?.toLowerCase() === filter);
Filtering logic can be moved to a "utils" file to keep this file cleaner

2024-12-26 19:24 UTC, alesha712 commented on src/components/container/layout/Footer.jsx
> +            <ul className="space-y-2">
Extract Quick links to a separat ecomponent for making it easier to maintain

2024-12-26 19:24 UTC, alesha712 commented on src/components/container/layout/Footer.jsx
> +              Email: support@teahaven.com<br />
Store email and phone information in a configuration file or environment variable - this to simplify updates

2024-12-26 19:24 UTC, alesha712 commented on src/components/container/layout/Header.jsx
> +  return (
To follow the single responsibility principle, move cerate a component for the auth links:
```jsx
const AuthLinks = ({ isAuthenticated, user }) => {
  if (isAuthenticated) {
    return (
      <div className="flex items-center space-x-4">
        <span className="text-gray-600">Welcome, {user?.name || 'Guest'}</span>
        <Link to="/profile" className="text-indigo-600 hover:text-indigo-800">
          Profile
        </Link>
      </div>
    );
  }
  return (
    <div>
      <Link to="/login" className="text-indigo-600 hover:text-indigo-800 mr-4">
        Sign In
      </Link>
      <Link to="/register" className="bg-indigo-600 text-white px-4 py-2 rounded hover:bg-indigo-700">
        Register
      </Link>
    </div>
  );
};
```

And use it like:
```jsx
const Header = () => {
  const { isAuthenticated, user } = useAuth();

  return (
    <header className="bg-white shadow">
      <nav className="container mx-auto px-4 py-4">
        <div className="flex justify-between items-center">
          <Link to="/" className="text-2xl font-bold text-indigo-600">
            Tea Haven
          </Link>
          <AuthLinks isAuthenticated={isAuthenticated} user={user} />
        </div>
      </nav>
    </header>
  );
};

export default Header;
```

2024-12-26 19:24 UTC, alesha712 commented on src/components/presentational/auth/ForgotPasswordForm.jsx
> +      const response = await axios.post(
Should be in a separate file - maybe a hook?

```jsx
// hooks/useForgotPassword.js
import { useState } from 'react';
import axios from 'axios';

export const useForgotPassword = () => {
  const [isLoading, setIsLoading] = useState(false);
  const [message, setMessage] = useState('');

  const sendForgotPasswordEmail = async (email) => {
    setIsLoading(true);
    try {
      const response = await axios.post(
        `${process.env.REACT_APP_API_URL}/api/auth/forgot-password`,
        { email }
      );
      setMessage(response.data.message);
    } catch (error) {
      setMessage(error.response?.data?.message || 'An error occurred');
    } finally {
      setIsLoading(false);
    }
  };

  return { isLoading, message, sendForgotPasswordEmail };
};
```

and use it like:
```jsx
const ForgotPasswordForm = () => {
  const [email, setEmail] = useState('');
  const { isLoading, message, sendForgotPasswordEmail } = useForgotPassword();

  const handleSubmit = (e) => {
    e.preventDefault();
    sendForgotPasswordEmail(email);
  };
```

2024-12-26 19:24 UTC, alesha712 commented on src/pages/Profile.jsx
> +              <form onSubmit={handlePasswordChange} className="mt-4 space-y-4">
Move the password form a separtae component

2024-12-26 19:24 UTC, alesha712 commented on src/App.jsx
@benzybert

2024-12-26 19:24 UTC, alesha712 commented on src/App.jsx
@benzybert

2024-12-30 09:00 UTC, benzybert commented on src/App.jsx
fix.

2025-01-09 13:51 UTC, merged